<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageReference Include="MimeKit" Version="4.18.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProductivityToolModels\ProductivityToolModels.csproj" />
    <ProjectReference Include="..\ProductivityToolDataServices\ProductivityToolDataServices.csproj" />
  </ItemGroup>
</Project>
